/* Horus content platform — an integrated registry for community mods,
   resource packs and shaders, plus server packs that bundle content +
   settings for one-click joining.

   Local-first and open by design:
   - the registry is a plain JSON file + a file store on your disk,
   - uploads are validated (real zip, metadata extracted) and enter a
     review queue; an admin approves/rejects and can mark items verified,
   - installs drop the exact reviewed files into the profile's standard
     mods/ · resourcepacks/ · shaderpacks/ folders,
   - an install ledger per profile powers "update available" detection,
   - a `contentRegistry` URL can point at a shared, self-hostable registry
     that speaks this same API (so no vendor lock-in).

   There are no secrets and no telemetry — everything here is inspectable. */

import path from 'node:path';
import { promises as fsp } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirs, getSettings, getProfile, profileGameDir } from './store.js';
import { readJson, writeJson, ensureDir, sha1, exists } from './util.js';
import { listEntries, readZipFile, writeZip } from './zip.js';
import { fetchJson } from './net.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));

const TYPES = {
  mod: { dir: 'mods', ext: '.jar' },
  resourcepack: { dir: 'resourcepacks', ext: '.zip' },
  shader: { dir: 'shaderpacks', ext: '.zip' },
};

const MAX_UPLOAD = 160 * 1024 * 1024; // 160 MB

let registry = null;     // { content: [...], serverpacks: [...] }
let installed = null;    // { [profileId]: [ {contentId, version, file, type} ] }

const registryFile = () => path.join(dirs().content, 'registry.json');
const installedFile = () => path.join(dirs().content, 'installed.json');
const filesDir = () => path.join(dirs().content, 'files');

/* ------------------------------------------------------------- persistence */

async function loadRegistry() {
  if (registry) return registry;
  registry = await readJson(registryFile(), null);
  if (!registry || !Array.isArray(registry.content)) {
    registry = await seedRegistry();
    await saveRegistry();
  }
  return registry;
}

async function saveRegistry() {
  await writeJson(registryFile(), registry);
}

async function loadInstalled() {
  if (installed) return installed;
  installed = await readJson(installedFile(), {}) || {};
  return installed;
}

async function saveInstalled() {
  await writeJson(installedFile(), installed);
}

async function seedRegistry() {
  const seed = await readJson(path.join(HERE, 'fixtures', 'content-seed.json'), null);
  if (!seed || !Array.isArray(seed.content)) return { content: [], serverpacks: [] };

  const content = [];
  for (const raw of seed.content) {
    const version = raw.version || '1.0.0';
    // Generate a small, valid placeholder archive so install/update work
    // fully offline. Horus never ships third-party bytes.
    const inner = {
      'horus-placeholder.txt':
        `${raw.name} v${version} by ${raw.author}\n${raw.summary || ''}\n\n` +
        'Placeholder generated by Horus for the local content library. Replace by ' +
        'uploading the real file, or point contentRegistry at a shared registry.',
    };
    if (raw.type === 'mod' && (raw.loaders || []).includes('fabric')) {
      inner['fabric.mod.json'] = JSON.stringify({ schemaVersion: 1, id: raw.id, name: raw.name, version });
    }
    if (raw.type === 'resourcepack' || raw.type === 'shader') {
      inner['pack.mcmeta'] = JSON.stringify({ pack: { pack_format: 34, description: raw.summary || raw.name } });
    }
    const buf = writeZip(inner);
    const ext = TYPES[raw.type].ext;
    const rel = path.join('files', raw.id, `${sanitize(raw.name)}-${sanitize(version)}${ext}`);
    await ensureDir(path.dirname(path.join(dirs().content, rel)));
    await fsp.writeFile(path.join(dirs().content, rel), buf);

    const [ratingAvg, ratingCount] = raw.rating || [0, 0];
    content.push({
      id: raw.id,
      type: raw.type,
      name: raw.name,
      author: raw.author,
      summary: raw.summary || '',
      category: raw.category || 'misc',
      versions: raw.versions || ['1.21.5'],
      loaders: raw.loaders || [],
      status: 'approved',
      verified: !!raw.verified,
      source: 'seed',
      downloads: raw.downloads || 0,
      ratingSum: Math.round(ratingAvg * ratingCount),
      ratingCount,
      latest: { version, file: rel, sha1: sha1(buf), size: buf.length, uploadedAt: Date.now() - (raw.downloads || 0) },
      fileHistory: [],
    });
  }
  return { content, serverpacks: seed.serverpacks || [] };
}

/* ------------------------------------------------------------------ helpers */

function publicView(c) {
  const { fileHistory, ...rest } = c;
  void fileHistory;
  return {
    ...rest,
    rating: c.ratingCount ? Math.round((c.ratingSum / c.ratingCount) * 10) / 10 : 0,
  };
}

function matchFilter(c, f) {
  if (f.type && c.type !== f.type) return false;
  if (f.status && c.status !== f.status) return false;
  if (f.category && c.category !== f.category) return false;
  if (f.version && !(c.versions || []).includes(f.version)) return false;
  if (f.loader && c.type === 'mod' && (c.loaders || []).length && !c.loaders.includes(f.loader)) return false;
  if (f.verified && !c.verified) return false;
  if (f.query) {
    const hay = `${c.name} ${c.author} ${c.summary}`.toLowerCase();
    if (!hay.includes(f.query.toLowerCase())) return false;
  }
  return true;
}

function sortContent(list, sort) {
  const arr = [...list];
  if (sort === 'newest') arr.sort((a, b) => (b.latest?.uploadedAt || 0) - (a.latest?.uploadedAt || 0));
  else if (sort === 'rating') arr.sort((a, b) => (b.ratingSum / (b.ratingCount || 1)) - (a.ratingSum / (a.ratingCount || 1)));
  else arr.sort((a, b) => (b.downloads || 0) - (a.downloads || 0)); // popular
  return arr;
}

/* --------------------------------------------------------------- read APIs */

export async function listContent(filter = {}) {
  // Remote registry: proxy the query (read-only) so a shared library works.
  const remote = getSettings().contentRegistry;
  if (remote) {
    try {
      const params = new URLSearchParams(
        Object.entries(filter).filter(([, v]) => v !== undefined && v !== '' && v !== false),
      );
      const data = await fetchJson(`${remote.replace(/\/+$/, '')}/api/content?${params}`, { proxy: getSettings().proxy || undefined });
      return data.content || [];
    } catch { /* fall back to local registry below */ }
  }
  const reg = await loadRegistry();
  const status = filter.status || 'approved';
  const list = reg.content.filter((c) => matchFilter(c, { ...filter, status }));
  return sortContent(list, filter.sort).map(publicView);
}

export async function categories() {
  const reg = await loadRegistry();
  const set = new Set();
  for (const c of reg.content) if (c.category) set.add(c.category);
  return [...set].sort();
}

export async function pendingCount() {
  const reg = await loadRegistry();
  return reg.content.filter((c) => c.status === 'pending').length;
}

/* ------------------------------------------------------------------ upload */

async function extractMeta(type, buf, tmpPath) {
  // Validate it is a real archive first.
  try { listEntries(buf); } catch { throw new Error('not a valid .zip/.jar archive'); }
  await ensureDir(path.dirname(tmpPath));
  await fsp.writeFile(tmpPath, buf);
  const out = {};
  try {
    if (type === 'mod') {
      const fabric = await readZipFile(tmpPath, 'fabric.mod.json');
      if (fabric) {
        const j = JSON.parse(fabric.toString('utf8'));
        out.name = j.name; out.version = j.version; out.summary = j.description;
        out.loaders = ['fabric'];
      } else if (await readZipFile(tmpPath, 'META-INF/mods.toml') || await readZipFile(tmpPath, 'META-INF/neoforge.mods.toml')) {
        out.loaders = ['forge', 'neoforge'];
      }
    } else if (type === 'resourcepack' || type === 'shader') {
      const mcmeta = await readZipFile(tmpPath, 'pack.mcmeta');
      if (mcmeta) {
        const j = JSON.parse(mcmeta.toString('utf8'));
        out.summary = j.pack?.description && typeof j.pack.description === 'string' ? j.pack.description : undefined;
      } else if (type === 'resourcepack') {
        throw new Error('resource pack is missing pack.mcmeta');
      }
    }
  } finally {
    await fsp.rm(tmpPath, { force: true });
  }
  return out;
}

/**
 * @param {object} meta { type, name, author, summary, category, versions[], loaders[], version }
 * @param {Buffer} buf  the uploaded file
 */
export async function uploadContent(meta, buf) {
  if (!TYPES[meta.type]) throw new Error('type must be mod, resourcepack or shader');
  if (buf.length > MAX_UPLOAD) throw new Error(`file too large (max ${MAX_UPLOAD / 1048576} MB)`);
  if (buf.length < 8) throw new Error('empty file');

  const reg = await loadRegistry();
  const tmp = path.join(dirs().content, 'tmp', `up-${Date.now()}`);
  const detected = await extractMeta(meta.type, buf, tmp);

  const name = (meta.name || detected.name || 'Untitled').toString().slice(0, 80);
  const version = (meta.version || detected.version || '1.0.0').toString().slice(0, 40);
  const hash = sha1(buf);
  const id = `usr-${sha1(name + meta.author).slice(0, 8)}`;

  const dest = path.join(filesDir(), id, `${sanitize(name)}-${sanitize(version)}${TYPES[meta.type].ext}`);
  await ensureDir(path.dirname(dest));
  await fsp.writeFile(dest, buf);

  const fileRec = {
    version,
    file: path.relative(dirs().content, dest),
    sha1: hash,
    size: buf.length,
    uploadedAt: Date.now(),
  };

  let entry = reg.content.find((c) => c.id === id);
  if (entry) {
    // New version of an existing upload → back to review.
    entry.fileHistory = entry.fileHistory || [];
    if (entry.latest) entry.fileHistory.push(entry.latest);
    entry.latest = fileRec;
    entry.status = 'pending';
    entry.verified = false;
    entry.summary = (meta.summary || detected.summary || entry.summary || '').toString().slice(0, 300);
    entry.versions = meta.versions?.length ? meta.versions : entry.versions;
  } else {
    entry = {
      id,
      type: meta.type,
      name,
      author: (meta.author || 'anonymous').toString().slice(0, 60),
      summary: (meta.summary || detected.summary || '').toString().slice(0, 300),
      category: (meta.category || 'misc').toString().slice(0, 40),
      versions: Array.isArray(meta.versions) && meta.versions.length ? meta.versions.slice(0, 20) : ['1.21.5'],
      loaders: meta.loaders?.length ? meta.loaders : (detected.loaders || []),
      status: 'pending',
      verified: false,
      source: 'community',
      downloads: 0,
      ratingSum: 0,
      ratingCount: 0,
      latest: fileRec,
      fileHistory: [],
    };
    reg.content.push(entry);
  }
  await saveRegistry();
  return publicView(entry);
}

function sanitize(s) {
  return String(s).replace(/[^a-zA-Z0-9._-]+/g, '_').slice(0, 60) || 'file';
}

/* ------------------------------------------------------------------ review */

function requireAdmin() {
  if (!getSettings().contentAdmin) {
    const e = new Error('content review is disabled on this instance (Settings → General → “I moderate this registry”)');
    e.code = 403;
    throw e;
  }
}

export async function reviewContent(id, action) {
  requireAdmin();
  const reg = await loadRegistry();
  const c = reg.content.find((x) => x.id === id);
  if (!c) { const e = new Error('unknown content'); e.code = 404; throw e; }
  if (action === 'approve') { c.status = 'approved'; c.reviewedAt = Date.now(); }
  else if (action === 'reject') { c.status = 'rejected'; c.reviewedAt = Date.now(); }
  else if (action === 'verify') { c.status = 'approved'; c.verified = true; c.reviewedAt = Date.now(); }
  else if (action === 'unverify') { c.verified = false; }
  else throw new Error('action must be approve, reject, verify or unverify');
  await saveRegistry();
  return publicView(c);
}

export async function rateContent(id, stars) {
  const reg = await loadRegistry();
  const c = reg.content.find((x) => x.id === id);
  if (!c) { const e = new Error('unknown content'); e.code = 404; throw e; }
  const n = Math.max(1, Math.min(5, Math.round(Number(stars) || 0)));
  c.ratingSum = (c.ratingSum || 0) + n;
  c.ratingCount = (c.ratingCount || 0) + 1;
  await saveRegistry();
  return publicView(c);
}

/* ----------------------------------------------------------------- install */

async function resolveFileBuffer(c) {
  // Local file store, or (roadmap) fetch from a remote registry's download URL.
  const local = path.join(dirs().content, c.latest.file);
  if (await exists(local)) return await fsp.readFile(local);
  const remote = getSettings().contentRegistry;
  if (remote) {
    const { fetchBuf } = await import('./net.js');
    const res = await fetchBuf(`${remote.replace(/\/+$/, '')}/api/content/${encodeURIComponent(c.id)}/download`, { proxy: getSettings().proxy || undefined });
    if (res.status === 200) return res.body;
  }
  throw new Error('content file not found in the store');
}

export async function installContent(id, profileId) {
  const profile = getProfile(profileId);
  if (!profile) { const e = new Error('unknown profile'); e.code = 404; throw e; }
  const reg = await loadRegistry();
  const c = reg.content.find((x) => x.id === id);
  if (!c) { const e = new Error('unknown content'); e.code = 404; throw e; }
  if (c.status !== 'approved') throw new Error('only approved content can be installed');

  const buf = await resolveFileBuffer(c);
  if (c.latest.sha1 && sha1(buf) !== c.latest.sha1) throw new Error('content failed integrity check');

  const targetDir = path.join(profileGameDir(profile), TYPES[c.type].dir);
  await ensureDir(targetDir);
  const filename = path.basename(c.latest.file);
  await fsp.writeFile(path.join(targetDir, filename), buf);

  // Update ledger: replace any prior install of this content in this profile.
  const led = await loadInstalled();
  led[profileId] = (led[profileId] || []).filter((e) => e.contentId !== id);
  // Remove stale files from earlier versions we recorded.
  for (const old of (installed[profileId] || [])) void old;
  led[profileId].push({ contentId: id, version: c.latest.version, file: filename, type: c.type });
  await saveInstalled();

  c.downloads = (c.downloads || 0) + 1;
  await saveRegistry();
  return { installed: filename, version: c.latest.version, dir: TYPES[c.type].dir };
}

export async function installedFor(profileId) {
  const led = await loadInstalled();
  return led[profileId] || [];
}

/** Compare installed versions against the registry's latest → update list. */
export async function checkUpdates(profileId) {
  const reg = await loadRegistry();
  const led = await installedFor(profileId);
  const updates = [];
  for (const rec of led) {
    const c = reg.content.find((x) => x.id === rec.contentId);
    if (c && c.status === 'approved' && c.latest.version !== rec.version) {
      updates.push({ id: c.id, name: c.name, type: c.type, from: rec.version, to: c.latest.version });
    }
  }
  return updates;
}

export async function updateAll(profileId) {
  const updates = await checkUpdates(profileId);
  const done = [];
  for (const u of updates) {
    // remove the old file first so we don't leave two versions behind
    const led = await installedFor(profileId);
    const rec = led.find((e) => e.contentId === u.id);
    if (rec) {
      const profile = getProfile(profileId);
      await fsp.rm(path.join(profileGameDir(profile), TYPES[rec.type].dir, rec.file), { force: true });
    }
    await installContent(u.id, profileId);
    done.push(u);
  }
  return done;
}

/* -------------------------------------------------------------- server packs */

export async function listServerPacks() {
  const reg = await loadRegistry();
  return reg.serverpacks || [];
}

/**
 * Materialize a server pack: create/refresh a profile, install every piece of
 * bundled content, return the profile id ready to launch onto the server.
 */
export async function joinServerPack(packId) {
  const reg = await loadRegistry();
  const pack = (reg.serverpacks || []).find((p) => p.id === packId);
  if (!pack) { const e = new Error('unknown server pack'); e.code = 404; throw e; }

  const store = await import('./store.js');
  const profileId = `srv-${pack.id}`;
  await store.upsertProfile(profileId, {
    name: `${pack.name} (server)`,
    version: pack.version,
    loader: pack.loader || 'fabric',
    ramMb: pack.ramMb || getSettings().defaultRamMb,
  });

  const results = [];
  for (const cid of pack.content || []) {
    try { results.push(await installContent(cid, profileId)); }
    catch (e) { results.push({ error: e.message, id: cid }); }
  }
  return { profileId, address: pack.address, installed: results, settings: pack.settings || {} };
}

/** Content a server recommends (superset used by the "for this server" view). */
export async function recommendedFor(packId) {
  const reg = await loadRegistry();
  const pack = (reg.serverpacks || []).find((p) => p.id === packId);
  if (!pack) return [];
  const ids = new Set([...(pack.content || []), ...(pack.recommended || [])]);
  return reg.content.filter((c) => ids.has(c.id) && c.status === 'approved').map(publicView);
}

/** Serve a content file's bytes (used by install + remote mirrors). */
export async function contentFile(id) {
  const reg = await loadRegistry();
  const c = reg.content.find((x) => x.id === id);
  if (!c || c.status !== 'approved') return null;
  const local = path.join(dirs().content, c.latest.file);
  if (!(await exists(local))) return null;
  return { buf: await fsp.readFile(local), name: path.basename(c.latest.file), type: c.type };
}
